### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by allangrds** [allangrds/pagarme-payment-service-provider#1]
### V1

- [x] Criar documentação;
- [x] Dockerizar aplicação;
- [x] Middleware validando payload com Joi;
- [ ] Criar error handler global;
- [ ] Criar exceptions customizadas;
- [ ] Criar log;
- [x] Gerar api_key só pra "frescura" (dividir transações da galera);
- [ ] Criar transações;
- [ ] Criar payables;
- [ ] Criar auth;
- [x] Criar users;
- [ ] Exigir autenticação para acessar as rotas;
- [ ] Criar cache de queries no redis;
- [ ] Set timeout;
- [ ] Rate limit;
- [ ] Criar docker específico para rodar os testes;
- [x] Inserir `Helmet`
- [x] Inserir Coderalls para garantir testes de cobertura
- [ ] Inserir ferramenta de log(winston, escriba)
- [ ] Separar ambiente de test e development para executar os testes

**Comment by allangrds** [comment]
- [ ] Inserir `Helmet`

**Comment by allangrds** [comment]
- Inserir Coderalls para garantir testes de cobertura

**Comment by allangrds** [comment]
- [ ] Inserir ferramenta de log(winston, escriba)
